/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetTokens'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/swap/status/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetSwapStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['GetQuote'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CheckHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TokenModel: {
      address: string;
      symbol: string;
      name: string;
      /** Format: double */
      decimals: number;
      chain: string;
      logoURI: string | null;
    };
    SwapStatusModel: {
      status: string;
      sourceChainHashes?: string[];
      sourceChainTxUrls?: string[];
      processorHashes?: string[];
      targetChainHashes?: string[];
      targetChainTxUrls?: string[];
    };
    /** @description 20 byte Ethereum address encoded as a hex with `0x` prefix. */
    Address: string;
    /** @description Amount of a token. `uint256` encoded in decimal. */
    TokenAmount: string;
    /** @description 32 bytes encoded as hex with `0x` prefix.
     *     It's expected to be the hash of the stringified JSON object representing the `appData`. */
    AppDataHash: string;
    /**
     * @description Is this order a buy or sell?
     * @enum {string}
     */
    OrderKind: 'buy' | 'sell';
    /**
     * @description Where should the `sellToken` be drawn from?
     * @enum {string}
     */
    SellTokenSource: 'erc20' | 'internal' | 'external';
    /**
     * @description Where should the `buyToken` be transferred to?
     * @enum {string}
     */
    BuyTokenDestination: 'erc20' | 'internal';
    /**
     * @description How was the order signed?
     * @enum {string}
     */
    SigningScheme: 'eip712' | 'ethsign' | 'presign' | 'eip1271';
    /** @description Order parameters. */
    OrderParameters: {
      signingScheme?: components['schemas']['SigningScheme'];
      buyTokenBalance?: components['schemas']['BuyTokenDestination'];
      sellTokenBalance?: components['schemas']['SellTokenSource'];
      /** @description Is the order fill-or-kill or partially fillable? */
      partiallyFillable: boolean;
      /** @description The kind is either a buy or sell order. */
      kind: components['schemas']['OrderKind'];
      /** @description feeRatio * sellAmount + minimal_fee in atoms. */
      feeAmount: components['schemas']['TokenAmount'];
      appData: components['schemas']['AppDataHash'];
      /**
       * Format: double
       * @description Unix timestamp (`uint32`) until which the order is valid.
       */
      validTo: number;
      /** @description Amount of `buyToken` to be bought in atoms. */
      buyAmount: components['schemas']['TokenAmount'];
      /** @description Amount of `sellToken` to be sold in atoms. */
      sellAmount: components['schemas']['TokenAmount'];
      /** @description An optional Ethereum address to receive the proceeds of the trade instead of the owner (i.e. the order signer). */
      receiver?: components['schemas']['Address'] | null;
      /** @description ERC-20 token to be bought. */
      buyToken: components['schemas']['Address'];
      /** @description ERC-20 token to be sold. */
      sellToken: components['schemas']['Address'];
    };
    /** @description An order quoted by the backend that can be directly signed and
     *     submitted to the order creation backend. */
    CowswapQuote: {
      /** @description Whether it was possible to verify that the quoted amounts are accurate using a simulation. */
      verified: boolean;
      /**
       * Format: double
       * @description Quote ID linked to a quote to enable providing more metadata when analysing order slippage.
       */
      id?: number;
      /** @description Expiration date of the offered fee. Order service might not accept
       *     the fee after this expiration date. Encoded as ISO 8601 UTC. */
      expiration: string;
      from?: components['schemas']['Address'];
      quote: components['schemas']['OrderParameters'];
    };
    /**
     * @description Whether to use the amount as the output or the input for the basis of the swap:
     *     - `EXACT_INPUT` - request output amount for exact input.
     *     - `EXACT_OUTPUT` - request output amount for exact output. The `refundTo` address will always receive excess tokens back even after the swap is complete.
     * @enum {string}
     */
    'QuoteRequest.swapType': 'EXACT_INPUT' | 'EXACT_OUTPUT';
    /**
     * @description Type of the deposit address:
     *     - `ORIGIN_CHAIN` - deposit address on the origin chain
     *     - `INTENTS` - **account ID** inside near intents to which you should transfer assets inside intents.
     * @enum {string}
     */
    'QuoteRequest.depositType': 'ORIGIN_CHAIN' | 'INTENTS';
    /**
     * @description Type of refund address:
     *     - `ORIGIN_CHAIN` - assets will be refunded to `refundTo` address on the origin chain
     *     - `INTENTS` - assets will be refunded to `refundTo` intents account
     * @enum {string}
     */
    'QuoteRequest.refundType': 'ORIGIN_CHAIN' | 'INTENTS';
    /**
     * @description Type of recipient address:
     *     - `DESTINATION_CHAIN` - assets will be transferred to chain of `destinationAsset`
     *     - `INTENTS` - assets will be transferred to account inside intents
     * @enum {string}
     */
    'QuoteRequest.recipientType': 'DESTINATION_CHAIN' | 'INTENTS';
    AppFee: {
      /**
       * Format: double
       * @description Fee for this recipient as part of amountIn in basis points (1/100th of a percent), e.g. 100 for 1% fee
       */
      fee: number;
      /** @description Intents Account ID where this fee will be transferred to */
      recipient: string;
    };
    QuoteRequest: {
      /** @description List of recipients and their fees */
      appFees?: components['schemas']['AppFee'][];
      /**
       * Format: double
       * @description Time in milliseconds user is willing to wait for quote from relay.
       */
      quoteWaitingTimeMs?: number;
      /** @description Referral identifier(lower case only) */
      referral?: string;
      /** @description Timestamp in ISO format, that identifies when user refund will begin if the swap isn't completed by then. */
      deadline: string;
      /** @description Type of recipient address:
       *     - `DESTINATION_CHAIN` - assets will be transferred to chain of `destinationAsset`
       *     - `INTENTS` - assets will be transferred to account inside intents */
      recipientType: components['schemas']['QuoteRequest.recipientType'];
      /** @description Recipient address. The format should match `recipientType`. */
      recipient: string;
      /** @description Type of refund address:
       *     - `ORIGIN_CHAIN` - assets will be refunded to `refundTo` address on the origin chain
       *     - `INTENTS` - assets will be refunded to `refundTo` intents account */
      refundType: components['schemas']['QuoteRequest.refundType'];
      /** @description Address for user refund. */
      refundTo: string;
      /** @description Amount to swap as the base amount (can be switched to exact input/output using the dedicated flag), denoted in the smallest unit of the specified currency (e.g., wei for ETH). */
      amount: string;
      /** @description ID of the destination asset. */
      destinationAsset: string;
      /** @description Type of the deposit address:
       *     - `ORIGIN_CHAIN` - deposit address on the origin chain
       *     - `INTENTS` - **account ID** inside near intents to which you should transfer assets inside intents. */
      depositType: components['schemas']['QuoteRequest.depositType'];
      /** @description ID of the origin asset. */
      originAsset: string;
      /**
       * Format: double
       * @description Slippage tolerance for the swap. This value is in basis points (1/100th of a percent), e.g. 100 for 1% slippage.
       */
      slippageTolerance: number;
      /** @description Whether to use the amount as the output or the input for the basis of the swap:
       *     - `EXACT_INPUT` - request output amount for exact input.
       *     - `EXACT_OUTPUT` - request output amount for exact output. The `refundTo` address will always receive excess tokens back even after the swap is complete. */
      swapType: components['schemas']['QuoteRequest.swapType'];
      /** @description Flag indicating whether this is a dry run request.
       *     If `true`, the response will **NOT** contain the following fields:
       *     - `depositAddress`
       *     - `timeWhenInactive`
       *     - `deadline` */
      dry: boolean;
    };
    Quote: {
      /**
       * Format: double
       * @description Estimated time in seconds for swap to be executed after the deposit transaction is confirmed
       */
      timeEstimate: number;
      /** @description Time when the deposit address will become cold and swap processing will take more time */
      timeWhenInactive?: string;
      /** @description Time when the deposit address will become inactive and funds might be lost */
      deadline?: string;
      /** @description Minimum amount with slippage taken into account */
      minAmountOut: string;
      /** @description Amount of the destination asset equivalent in USD */
      amountOutUsd: string;
      /** @description Amount of the destination asset in readable format */
      amountOutFormatted: string;
      /** @description Amount of the destination asset */
      amountOut: string;
      /** @description Minimum amount of the origin asset that will be used for swap */
      minAmountIn: string;
      /** @description Amount of the origin assets equivalent in USD */
      amountInUsd: string;
      /** @description Amount of the origin asset in readable format */
      amountInFormatted: string;
      /** @description Amount of the origin asset */
      amountIn: string;
      /** @description The deposit address on the chain of `originAsset` in case if `depositType` is `ORIGIN_CHAIN`.
       *
       *     The deposit address inside of near intents (the verifier smart contract) in case if `depositType` is `INTENTS`. */
      depositAddress?: string;
    };
    NearIntentsQuote: {
      /** @description Response that contains the deposit address to send "amount" of `originAsset` and possible output amount. */
      quote: components['schemas']['Quote'];
      /** @description User request */
      quoteRequest: components['schemas']['QuoteRequest'];
      /** @description Signature of the 1Click service confirming the quote for the specific deposit address. Must be saved on the client side (along with the whole quote) in order to resolve any disputes or mistakes. */
      signature: string;
      /** @description Timestamp in ISO format that took part in the deposit address derivation */
      timestamp: string;
    };
    QuoteResponseModel: {
      /** @example 10000 */
      amountTo: string;
      originalQuote: components['schemas']['CowswapQuote'] | components['schemas']['NearIntentsQuote'];
      /**
       * @example COWSWAP
       * @enum {string}
       */
      quoteSource: 'NEARINTENTS' | 'COWSWAP' | '1INCH';
    };
    /** @enum {string} */
    QuoteKind: 'EXACT_INPUT' | 'EXACT_OUTPUT';
    QuoteRequestModel: {
      amount: string;
      accountFrom: string;
      tokenFrom: string;
      chainFrom: string;
      accountTo?: string;
      tokenTo: string;
      chainTo: string;
      /** Format: double */
      slippage: number;
      kind: components['schemas']['QuoteKind'];
      /** Format: double */
      ttl: number;
      appData?: string;
      isSmartContractWallet?: boolean;
      isNative?: boolean;
      requestId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenModel'][];
        };
      };
    };
  };
  GetSwapStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SwapStatusModel'];
        };
      };
      /** @description No swap found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetQuote: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuoteRequestModel'];
      };
    };
    responses: {
      /** @description Ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['QuoteResponseModel']
            | {
                error: string;
              };
        };
      };
      /** @description No quote found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  CheckHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            status: string;
          };
        };
      };
    };
  };
}
